# Database access — TTC GTFS-RT (VehiclePositions)

The Postgres/PostGIS container is published on **host port 5433** → container port 5432.

| setting  | value          |
|----------|----------------|
| host     | `localhost`    |
| port     | `5433`         |
| user     | `ttc`          |
| password | `ttc`          |
| database | `ttc_gtfsrt`   |

**URL forms**

- from a notebook / host shell: `postgresql+psycopg://ttc:ttc@localhost:5433/ttc_gtfsrt`
- from another compose service (api, collector, dashboard): `postgresql+psycopg://ttc:ttc@postgres:5432/ttc_gtfsrt`
- raw psql inside the container: `docker compose exec postgres psql -U ttc -d ttc_gtfsrt`

Tables in the current schema:

- `feed_fetch_logs` — one row per fetch attempt (success or failure)
- `raw_gtfsrt_snapshots` — raw protobuf bytes (one per successful fetch)
- `vehicle_positions` — normalized per-entity rows; includes `geom GEOMETRY(Point, 4326)` (PostGIS, generated from lon/lat)

In [1]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg://ttc:ttc@localhost:5433/ttc_gtfsrt")

### Recovering from a `PendingRollbackError`

If a previous query errored, the engine's pooled connection will refuse new work until the aborted transaction is rolled back. Dispose the engine and rebuild:

In [2]:
engine.dispose()
engine = create_engine("postgresql+psycopg://ttc:ttc@localhost:5433/ttc_gtfsrt")

## Schema overview

In [3]:
pd.read_sql("""
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public'
    ORDER BY table_name
""", engine)

             table_name
0       alembic_version
1       feed_fetch_logs
2     geography_columns
3      geometry_columns
4  raw_gtfsrt_snapshots
5       spatial_ref_sys
6     vehicle_positions

In [4]:
pd.read_sql("""
    SELECT column_name, data_type
    FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'vehicle_positions'
    ORDER BY ordinal_position
""", engine)

              column_name                 data_type
0                      id                    bigint
1             snapshot_id                    bigint
2              fetched_at  timestamp with time zone
3   feed_header_timestamp  timestamp with time zone
4               entity_id         character varying
5       vehicle_timestamp  timestamp with time zone
6              vehicle_id         character varying
7           vehicle_label         character varying
8                 trip_id         character varying
9                route_id         character varying
10           direction_id                  smallint
11             start_date         character varying
12             start_time         character varying
13  schedule_relationship         character varying
14               latitude          double precision
15              longitude          double precision
16                bearing          double precision
17               odometer          double precision
18              speed_mps          double precision
19         current_status         character varying
20  current_stop_sequence                   integer
21                stop_id         character varying
22       occupancy_status         character varying
23   occupancy_percentage                  smallint
24       congestion_level         character varying
25             raw_entity                     jsonb
26                   geom              USER-DEFINED

## Common queries

In [5]:
# Recent fetch attempts (success + failure)
pd.read_sql("""
    SELECT fetched_at, success, http_status, duration_ms, entity_count,
           error_type, error_message
    FROM feed_fetch_logs
    ORDER BY fetched_at DESC
    LIMIT 10
""", engine)

,fetched_at,success,http_status,duration_ms,entity_count,error_type,error_message
0,2026-04-22 01:53:38.097424+00:00,True,200,51,1473,None,None
1,2026-04-22 01:53:18.130070+00:00,True,200,45,1476,None,None
2,2026-04-22 01:52:58.157423+00:00,True,200,48,1475,None,None
3,2026-04-22 01:52:38.196507+00:00,True,200,48,1477,None,None
4,2026-04-22 01:52:18.223389+00:00,True,200,49,1477,None,None
5,2026-04-22 01:51:58.213647+00:00,True,200,55,1472,None,None
6,2026-04-22 01:51:38.242923+00:00,True,200,44,1472,None,None
7,2026-04-22 01:51:18.267725+00:00,True,200,44,1477,None,None
8,2026-04-22 01:50:58.279615+00:00,True,200,48,1477,None,None
9,2026-04-22 01:50:38.306084+00:00,True,200,46,1477,None,None

In [6]:
# Latest observation per vehicle (the "hot" query — indexed on (vehicle_id, fetched_at DESC))
pd.read_sql("""
    SELECT DISTINCT ON (vehicle_id)
           vehicle_id, route_id, trip_id, latitude, longitude,
           speed_mps, bearing, current_status, occupancy_status, fetched_at
    FROM vehicle_positions
    WHERE vehicle_id IS NOT NULL
      AND fetched_at > now() - interval '5 minutes'
    ORDER BY vehicle_id, fetched_at DESC
    LIMIT 50
""", engine)

,vehicle_id,route_id,trip_id,latitude,longitude,speed_mps,bearing,current_status,occupancy_status,fetched_at
0,1,None,None,43.658482,-79.325394,0.000000,0.0,None,None,2026-04-22 01:53:38.097424+00:00
1,1232,86,46947020,43.759838,-79.196770,10.728960,213.0,IN_TRANSIT_TO,EMPTY,2026-04-22 01:53:38.097424+00:00
2,1233,None,None,43.794838,-79.243935,0.000000,242.0,None,EMPTY,2026-04-22 01:53:38.097424+00:00
3,1236,130,112820020,43.809822,-79.257507,3.129280,346.0,INCOMING_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
4,1247,905,52429020,43.791508,-79.184624,1.788160,350.0,INCOMING_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
5,1253,None,None,43.793957,-79.243103,0.000000,337.0,None,EMPTY,2026-04-22 01:53:38.097424+00:00
6,1255,38,46242020,43.782776,-79.137993,13.858240,162.0,INCOMING_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
7,1259,86,32115020,43.783669,-79.169273,0.000000,181.0,STOPPED_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
8,1272,134,131990020,43.780136,-79.249596,0.000000,254.0,IN_TRANSIT_TO,EMPTY,2026-04-22 01:53:38.097424+00:00
9,1274,116,18659020,43.816360,-79.211540,0.000000,132.0,IN_TRANSIT_TO,EMPTY,2026-04-22 01:53:38.097424+00:00
10,1277,116,62574020,43.746227,-79.208969,6.705600,22.0,IN_TRANSIT_TO,EMPTY,2026-04-22 01:53:38.097424+00:00
11,1281,27,108000020,43.649963,-79.484032,0.000000,74.0,INCOMING_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
12,1301,None,None,43.788929,-79.236763,11.623040,344.0,None,EMPTY,2026-04-22 01:53:38.097424+00:00
13,1315,35,66675020,43.760036,-79.518410,8.493760,172.0,INCOMING_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
14,1321,35,95286020,43.688793,-79.486938,0.000000,78.0,STOPPED_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
15,1322,71,126837020,43.694290,-79.494827,3.129280,215.0,None,EMPTY,2026-04-22 01:53:38.097424+00:00
16,1323,41,8175020,43.775677,-79.500366,8.046720,341.0,INCOMING_AT,FEW_SEATS_AVAILABLE,2026-04-22 01:53:38.097424+00:00
17,1324,None,None,43.692871,-79.495338,0.000000,192.0,None,EMPTY,2026-04-22 01:53:38.097424+00:00
18,1325,None,None,43.692360,-79.494759,0.000000,22.0,None,EMPTY,2026-04-22 01:53:38.097424+00:00
19,1327,71,59511020,43.682266,-79.491547,0.447040,338.0,INCOMING_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
20,1328,27,4495020,43.688892,-79.488495,0.000000,129.0,None,EMPTY,2026-04-22 01:53:38.097424+00:00
21,1331,29,133226020,43.649460,-79.431252,0.000000,342.0,IN_TRANSIT_TO,EMPTY,2026-04-22 01:53:38.097424+00:00
22,1332,71,5053020,43.651733,-79.475952,0.000000,80.0,STOPPED_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
23,1333,112,124749020,43.641933,-79.565735,0.000000,341.0,STOPPED_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
24,1334,35,65366020,43.777020,-79.509048,0.000000,113.0,STOPPED_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
25,1342,171,57677020,43.687138,-79.489136,0.000000,258.0,INCOMING_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
26,1350,158,15126020,43.697693,-79.502136,0.894080,277.0,INCOMING_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
27,1353,35,38123020,43.689503,-79.500244,9.834880,348.0,INCOMING_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
28,1357,32,32026020,43.686771,-79.490425,10.728960,75.0,IN_TRANSIT_TO,EMPTY,2026-04-22 01:53:38.097424+00:00
29,1381,935,125341020,43.650036,-79.483597,0.000000,74.0,STOPPED_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
30,1382,158,11997020,43.708305,-79.532043,0.000000,257.0,INCOMING_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
31,1384,None,None,43.691669,-79.494965,0.000000,295.0,None,EMPTY,2026-04-22 01:53:38.097424+00:00
32,1386,506,6418020,43.664246,-79.402428,0.000000,342.0,STOPPED_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
33,1387,None,None,43.692493,-79.494736,0.000000,21.0,None,EMPTY,2026-04-22 01:53:38.097424+00:00
34,1396,935,127281020,43.776997,-79.509407,0.000000,115.0,STOPPED_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
35,1399,35,109435020,43.685532,-79.495178,13.858240,246.0,IN_TRANSIT_TO,EMPTY,2026-04-22 01:53:38.097424+00:00
36,1404,935,65069020,43.714672,-79.506958,8.493760,349.0,INCOMING_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
37,1406,102,19868020,43.729614,-79.227348,10.281919,221.0,INCOMING_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
38,1407,95,8924020,43.795269,-79.152130,4.470400,229.0,INCOMING_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
39,1409,45,91271020,43.645760,-79.537125,13.411200,162.0,IN_TRANSIT_TO,EMPTY,2026-04-22 01:53:38.097424+00:00
40,1412,102,73976020,43.729847,-79.226944,13.411200,40.0,INCOMING_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
41,1413,85,95144020,43.793617,-79.239388,0.447040,76.0,IN_TRANSIT_TO,EMPTY,2026-04-22 01:53:38.097424+00:00
42,1423,None,None,43.794449,-79.243324,0.000000,337.0,None,EMPTY,2026-04-22 01:53:38.097424+00:00
43,1503,95,80828020,43.745491,-79.406075,0.000000,130.0,STOPPED_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
44,1516,None,None,43.793854,-79.242996,0.000000,342.0,None,EMPTY,2026-04-22 01:53:38.097424+00:00
45,1529,85,129694020,43.809395,-79.171227,0.000000,242.0,INCOMING_AT,FEW_SEATS_AVAILABLE,2026-04-22 01:53:38.097424+00:00
46,1532,85,123157020,43.781036,-79.130112,4.917440,260.0,INCOMING_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
47,1534,905,132902020,43.786610,-79.188286,5.811520,127.0,IN_TRANSIT_TO,EMPTY,2026-04-22 01:53:38.097424+00:00
48,1536,116,37240020,43.801369,-79.199371,6.705600,347.0,INCOMING_AT,EMPTY,2026-04-22 01:53:38.097424+00:00
49,1549,133,10933020,43.733356,-79.263199,0.000000,164.0,INCOMING_AT,EMPTY,2026-04-22 01:53:38.097424+00:00

In [7]:
# Active vehicle count per route (last 15 min)
pd.read_sql("""
    WITH latest AS (
      SELECT DISTINCT ON (vehicle_id)
             vehicle_id, route_id, speed_mps, fetched_at
      FROM vehicle_positions
      WHERE fetched_at > now() - interval '15 minutes'
        AND vehicle_id IS NOT NULL
      ORDER BY vehicle_id, fetched_at DESC
    )
    SELECT route_id,
           count(*)                           AS active_vehicles,
           avg(speed_mps) * 3.6               AS avg_speed_kph,
           max(fetched_at)                    AS latest_seen
    FROM latest
    WHERE route_id IS NOT NULL
    GROUP BY route_id
    ORDER BY active_vehicles DESC
    LIMIT 20
""", engine)

   route_id  active_vehicles  avg_speed_kph                      latest_seen
0       506               25       8.046720 2026-04-22 01:53:38.097424+00:00
1       505               25       5.986759 2026-04-22 01:53:38.097424+00:00
2       504               25       7.982346 2026-04-22 01:53:38.097424+00:00
3       501               23      11.405351 2026-04-22 01:53:38.097424+00:00
4       102               21      22.224274 2026-04-22 01:53:38.097424+00:00
5        95               20      19.955865 2026-04-22 01:53:38.097424+00:00
6        53               20      14.162227 2026-04-22 01:53:38.097424+00:00
7        52               18      17.434560 2026-04-22 01:53:38.097424+00:00
8       939               16      22.128480 2026-04-22 01:53:38.097424+00:00
9        54               16      18.708624 2026-04-22 01:53:38.097424+00:00
10       85               14      11.725221 2026-04-22 01:53:38.097424+00:00
11       25               14      18.737362 2026-04-22 01:53:38.097424+00:00
12      116               13      23.644977 2026-04-22 01:53:38.097424+00:00
13       35               13      23.521181 2026-04-22 01:53:38.097424+00:00
14       29               13      12.255773 2026-04-22 01:53:38.097424+00:00
15      510               13       5.447010 2026-04-22 01:53:38.097424+00:00
16       41               13      13.865117 2026-04-22 01:53:38.097424+00:00
17       72               12       6.303264 2026-04-22 01:53:38.097424+00:00
18      503               12       9.521952 2026-04-22 01:53:38.097424+00:00
19       96               12      18.775680 2026-04-22 01:53:38.097424+00:00

In [8]:
# Occupancy breakdown over the last hour
pd.read_sql("""
    SELECT coalesce(occupancy_status, 'UNKNOWN') AS occupancy_status,
           count(*)                              AS n
    FROM vehicle_positions
    WHERE fetched_at > now() - interval '1 hour'
    GROUP BY 1
    ORDER BY n DESC
""", engine)

      occupancy_status       n
0                EMPTY  251802
1  FEW_SEATS_AVAILABLE   20627
2              UNKNOWN    1830
3                 FULL     726

## PostGIS examples

`vehicle_positions.geom` is a generated `GEOMETRY(Point, 4326)` column populated from `longitude`/`latitude`, with a GiST index.

In [9]:
# Latest positions inside a downtown-Toronto bounding box
pd.read_sql("""
    SELECT vehicle_id, route_id, latitude, longitude, fetched_at
    FROM vehicle_positions
    WHERE fetched_at > now() - interval '5 minutes'
      AND geom && ST_MakeEnvelope(-79.42, 43.63, -79.35, 43.68, 4326)
    ORDER BY fetched_at DESC
    LIMIT 50
""", engine)

   vehicle_id route_id   latitude  longitude                       fetched_at
0        4507      504  43.648010 -79.383179 2026-04-22 01:53:38.097424+00:00
1        4520      506  43.650246 -79.389359 2026-04-22 01:53:38.097424+00:00
2        4519      501  43.657154 -79.365166 2026-04-22 01:53:38.097424+00:00
3        4514      506  43.659290 -79.366585 2026-04-22 01:53:38.097424+00:00
4        4522      504  43.655281 -79.358704 2026-04-22 01:53:38.097424+00:00
5        4524      511  43.666630 -79.411346 2026-04-22 01:53:38.097424+00:00
6        4525      504  43.649948 -79.374176 2026-04-22 01:53:38.097424+00:00
7        4526      505  43.656769 -79.375893 2026-04-22 01:53:38.097424+00:00
8        4536      501  43.646755 -79.406189 2026-04-22 01:53:38.097424+00:00
9        4550      509  43.637554 -79.392372 2026-04-22 01:53:38.097424+00:00
10       4549      509  43.645271 -79.379242 2026-04-22 01:53:38.097424+00:00
11       4560      501  43.650711 -79.383690 2026-04-22 01:53:38.097424+00:00
12       4564      501  43.650768 -79.376724 2026-04-22 01:53:38.097424+00:00
13       3233      503  43.650070 -79.384285 2026-04-22 01:53:38.097424+00:00
14       3232     None  43.668438 -79.397614 2026-04-22 01:53:38.097424+00:00
15       4555      501  43.651566 -79.379494 2026-04-22 01:53:38.097424+00:00
16       4570      509  43.635769 -79.417503 2026-04-22 01:53:38.097424+00:00
17       4567      511  43.636898 -79.399841 2026-04-22 01:53:38.097424+00:00
18       4581      501  43.660255 -79.361954 2026-04-22 01:53:38.097424+00:00
19       4583      501  43.648945 -79.395027 2026-04-22 01:53:38.097424+00:00
20       4576      505  43.654274 -79.391617 2026-04-22 01:53:38.097424+00:00
21       4577      505  43.657330 -79.373390 2026-04-22 01:53:38.097424+00:00
22       4596      509  43.636173 -79.410149 2026-04-22 01:53:38.097424+00:00
23       3268     None  43.664989 -79.402817 2026-04-22 01:53:38.097424+00:00
24       8501       75  43.671196 -79.376404 2026-04-22 01:53:38.097424+00:00
25       8744     None  43.675083 -79.416321 2026-04-22 01:53:38.097424+00:00
26       8739      504  43.662766 -79.351547 2026-04-22 01:53:38.097424+00:00
27       8511      121  43.665714 -79.354706 2026-04-22 01:53:38.097424+00:00
28       8519      114  43.641747 -79.375061 2026-04-22 01:53:38.097424+00:00
29       8527       65  43.673450 -79.369133 2026-04-22 01:53:38.097424+00:00
30       7213      506  43.665047 -79.354340 2026-04-22 01:53:38.097424+00:00
31       8788      503  43.654785 -79.364197 2026-04-22 01:53:38.097424+00:00
32       8552      121  43.648090 -79.371445 2026-04-22 01:53:38.097424+00:00
33       8549       94  43.662956 -79.402351 2026-04-22 01:53:38.097424+00:00
34       7217      506  43.661671 -79.380341 2026-04-22 01:53:38.097424+00:00
35       8561      114  43.642536 -79.373085 2026-04-22 01:53:38.097424+00:00
36       8331      503  43.650875 -79.370216 2026-04-22 01:53:38.097424+00:00
37       7003      126  43.664108 -79.418655 2026-04-22 01:53:38.097424+00:00
38       7245      506  43.658474 -79.397095 2026-04-22 01:53:38.097424+00:00
39       8571       94  43.664001 -79.390823 2026-04-22 01:53:38.097424+00:00
40       7016        7  43.666378 -79.411140 2026-04-22 01:53:38.097424+00:00
41       9213      505  43.648361 -79.398239 2026-04-22 01:53:38.097424+00:00
42       8362       26  43.672298 -79.418442 2026-04-22 01:53:38.097424+00:00
43       8146      503  43.655655 -79.364357 2026-04-22 01:53:38.097424+00:00
44       7056       97  43.646194 -79.378548 2026-04-22 01:53:38.097424+00:00
45       9016        7  43.667572 -79.412094 2026-04-22 01:53:38.097424+00:00
46       9011        7  43.666782 -79.411842 2026-04-22 01:53:38.097424+00:00
47       4607      505  43.661285 -79.358002 2026-04-22 01:53:38.097424+00:00
48       4605      511  43.642815 -79.402245 2026-04-22 01:53:38.097424+00:00
49       4613      510  43.655048 -79.398933 2026-04-22 01:53:38.097424+00:00

In [10]:
# Vehicles currently within 500 m of Union Station (43.6453, -79.3806)
pd.read_sql("""
    SELECT DISTINCT ON (vehicle_id)
           vehicle_id, route_id,
           ST_DistanceSphere(geom, ST_SetSRID(ST_MakePoint(-79.3806, 43.6453), 4326)) AS meters,
           fetched_at
    FROM vehicle_positions
    WHERE fetched_at > now() - interval '5 minutes'
      AND ST_DWithin(geom::geography,
                     ST_SetSRID(ST_MakePoint(-79.3806, 43.6453), 4326)::geography,
                     500)
    ORDER BY vehicle_id, fetched_at DESC
""", engine)

   vehicle_id route_id      meters                       fetched_at
0        4424      510  121.433952 2026-04-22 01:53:38.097424+00:00
1        4461      504  424.325671 2026-04-22 01:53:38.097424+00:00
2        4507      504  365.886935 2026-04-22 01:53:38.097424+00:00
3        4525      504  469.866935 2026-04-22 01:51:58.213647+00:00
4        4549      509  109.320868 2026-04-22 01:53:38.097424+00:00
5        4564      501  498.672420 2026-04-22 01:50:38.306084+00:00
6        4649      504  456.045803 2026-04-22 01:53:38.097424+00:00
7        7056       97  192.775441 2026-04-22 01:53:38.097424+00:00
8        8437       19  216.327881 2026-04-22 01:53:38.097424+00:00
9        8519      114  456.665415 2026-04-22 01:53:18.130070+00:00
10       8552      121  459.792775 2026-04-22 01:50:58.279615+00:00
11       8647      503  355.161313 2026-04-22 01:53:38.097424+00:00

## Raw protobuf replay

`raw_gtfsrt_snapshots.payload` stores the exact bytes returned by the feed — useful for re-parsing or diagnostics.

In [12]:
from google.transit import gtfs_realtime_pb2

row = pd.read_sql(
    "SELECT payload FROM raw_gtfsrt_snapshots ORDER BY id DESC LIMIT 1", engine
)
payload_bytes = bytes(row["payload"].iloc[0])

msg = gtfs_realtime_pb2.FeedMessage()
msg.ParseFromString(payload_bytes)
print(f"entities: {len(msg.entity)}  header ts: {msg.header.timestamp}")
print(msg.entity[0])

entities: 1197  header ts: 1776828561
id: "1"
vehicle {
  trip {
    trip_id: "19649020"
    schedule_relationship: SCHEDULED
    route_id: "927"
  }
  position {
    latitude: 43.6433601
    longitude: -79.5619431
    bearing: 342
    speed: 26.8224
  }
  current_stop_sequence: 3
  current_status: IN_TRANSIT_TO
  timestamp: 1776828545
  stop_id: "4640"
  vehicle {
    id: "3640"
  }
  occupancy_status: FEW_SEATS_AVAILABLE
}